# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmmain.ui'
#
# Created: Mon Jun  5 21:04:11 2017
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_frmMain(object):
    def setupUi(self, frmMain):
        frmMain.setObjectName(_fromUtf8("frmMain"))
        frmMain.resize(845, 483)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frmMain.sizePolicy().hasHeightForWidth())
        frmMain.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        frmMain.setPalette(palette)
        self.centralWidget = QtGui.QWidget(frmMain)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.tabContainer = QtGui.QTabWidget(self.centralWidget)
        self.tabContainer.setGeometry(QtCore.QRect(20, 10, 801, 371))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.tabContainer.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tabContainer.setFont(font)
        self.tabContainer.setObjectName(_fromUtf8("tabContainer"))
        self.tabComms = QtGui.QWidget()
        self.tabComms.setObjectName(_fromUtf8("tabComms"))
        self.cmdSend = QtGui.QPushButton(self.tabComms)
        self.cmdSend.setGeometry(QtCore.QRect(700, 310, 75, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.cmdSend.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.cmdSend.setFont(font)
        self.cmdSend.setAutoFillBackground(True)
        self.cmdSend.setFlat(True)
        self.cmdSend.setObjectName(_fromUtf8("cmdSend"))
        self.cmdClear = QtGui.QPushButton(self.tabComms)
        self.cmdClear.setGeometry(QtCore.QRect(620, 310, 75, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.cmdClear.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.cmdClear.setFont(font)
        self.cmdClear.setAutoFillBackground(True)
        self.cmdClear.setAutoDefault(False)
        self.cmdClear.setFlat(True)
        self.cmdClear.setObjectName(_fromUtf8("cmdClear"))
        self.textBrowser = QtGui.QTextBrowser(self.tabComms)
        self.textBrowser.setGeometry(QtCore.QRect(150, 30, 621, 221))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowser.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.textBrowser.setFont(font)
        self.textBrowser.setReadOnly(False)
        self.textBrowser.setAcceptRichText(False)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.lblSendingTo = QtGui.QLabel(self.tabComms)
        self.lblSendingTo.setGeometry(QtCore.QRect(150, 10, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblSendingTo.setFont(font)
        self.lblSendingTo.setObjectName(_fromUtf8("lblSendingTo"))
        self.label_2 = QtGui.QLabel(self.tabComms)
        self.label_2.setGeometry(QtCore.QRect(236, 10, 321, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalScrollBar = QtGui.QScrollBar(self.tabComms)
        self.verticalScrollBar.setGeometry(QtCore.QRect(775, 40, 21, 231))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName(_fromUtf8("verticalScrollBar"))
        self.treeContacts = QtGui.QTreeWidget(self.tabComms)
        self.treeContacts.setGeometry(QtCore.QRect(10, 11, 131, 321))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.treeContacts.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.treeContacts.setFont(font)
        self.treeContacts.setAutoFillBackground(False)
        self.treeContacts.setFrameShape(QtGui.QFrame.NoFrame)
        self.treeContacts.setFrameShadow(QtGui.QFrame.Plain)
        self.treeContacts.setObjectName(_fromUtf8("treeContacts"))
        item_0 = QtGui.QTreeWidgetItem(self.treeContacts)
        item_0 = QtGui.QTreeWidgetItem(self.treeContacts)
        self.lineEdit_6 = QtGui.QLineEdit(self.tabComms)
        self.lineEdit_6.setGeometry(QtCore.QRect(150, 260, 621, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.tabContainer.addTab(self.tabComms, _fromUtf8(""))
        self.tabWeb = QtGui.QWidget()
        self.tabWeb.setObjectName(_fromUtf8("tabWeb"))
        self.tabContainer.addTab(self.tabWeb, _fromUtf8(""))
        self.tabProfile = QtGui.QWidget()
        self.tabProfile.setObjectName(_fromUtf8("tabProfile"))
        self.textBrowser_2 = QtGui.QTextBrowser(self.tabProfile)
        self.textBrowser_2.setGeometry(QtCore.QRect(480, 10, 311, 321))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setObjectName(_fromUtf8("textBrowser_2"))
        self.txtUserName = QtGui.QLineEdit(self.tabProfile)
        self.txtUserName.setGeometry(QtCore.QRect(102, 20, 361, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.txtUserName.setFont(font)
        self.txtUserName.setObjectName(_fromUtf8("txtUserName"))
        self.txtIPv6Address = QtGui.QLineEdit(self.tabProfile)
        self.txtIPv6Address.setGeometry(QtCore.QRect(100, 50, 361, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.txtIPv6Address.setFont(font)
        self.txtIPv6Address.setObjectName(_fromUtf8("txtIPv6Address"))
        self.lblBio = QtGui.QLabel(self.tabProfile)
        self.lblBio.setGeometry(QtCore.QRect(10, 80, 47, 13))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.lblBio.setFont(font)
        self.lblBio.setWordWrap(True)
        self.lblBio.setObjectName(_fromUtf8("lblBio"))
        self.lblV6Address = QtGui.QLabel(self.tabProfile)
        self.lblV6Address.setGeometry(QtCore.QRect(10, 50, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.lblV6Address.setFont(font)
        self.lblV6Address.setObjectName(_fromUtf8("lblV6Address"))
        self.lblUserName = QtGui.QLabel(self.tabProfile)
        self.lblUserName.setGeometry(QtCore.QRect(10, 20, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.lblUserName.setFont(font)
        self.lblUserName.setObjectName(_fromUtf8("lblUserName"))
        self.cmdUpdateProfile = QtGui.QPushButton(self.tabProfile)
        self.cmdUpdateProfile.setGeometry(QtCore.QRect(390, 200, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.cmdUpdateProfile.setFont(font)
        self.cmdUpdateProfile.setObjectName(_fromUtf8("cmdUpdateProfile"))
        self.cmdCancelProfile = QtGui.QPushButton(self.tabProfile)
        self.cmdCancelProfile.setGeometry(QtCore.QRect(300, 200, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.cmdCancelProfile.setFont(font)
        self.cmdCancelProfile.setObjectName(_fromUtf8("cmdCancelProfile"))
        self.txtBio = QtGui.QTextEdit(self.tabProfile)
        self.txtBio.setGeometry(QtCore.QRect(103, 80, 361, 111))
        self.txtBio.setFrameShadow(QtGui.QFrame.Plain)
        self.txtBio.setObjectName(_fromUtf8("txtBio"))
        self.tabContainer.addTab(self.tabProfile, _fromUtf8(""))
        self.tabConfig = QtGui.QWidget()
        self.tabConfig.setObjectName(_fromUtf8("tabConfig"))
        self.cmdSaveConfig = QtGui.QPushButton(self.tabConfig)
        self.cmdSaveConfig.setGeometry(QtCore.QRect(710, 300, 75, 23))
        self.cmdSaveConfig.setObjectName(_fromUtf8("cmdSaveConfig"))
        self.lblIPv6ConfigAddress = QtGui.QLabel(self.tabConfig)
        self.lblIPv6ConfigAddress.setGeometry(QtCore.QRect(10, 20, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblIPv6ConfigAddress.setFont(font)
        self.lblIPv6ConfigAddress.setObjectName(_fromUtf8("lblIPv6ConfigAddress"))
        self.lblPassword = QtGui.QLabel(self.tabConfig)
        self.lblPassword.setGeometry(QtCore.QRect(10, 50, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblPassword.setFont(font)
        self.lblPassword.setObjectName(_fromUtf8("lblPassword"))
        self.lblPrivateKey = QtGui.QLabel(self.tabConfig)
        self.lblPrivateKey.setGeometry(QtCore.QRect(10, 90, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblPrivateKey.setFont(font)
        self.lblPrivateKey.setObjectName(_fromUtf8("lblPrivateKey"))
        self.txtIPv6AddressConfig = QtGui.QLineEdit(self.tabConfig)
        self.txtIPv6AddressConfig.setGeometry(QtCore.QRect(100, 20, 341, 20))
        self.txtIPv6AddressConfig.setObjectName(_fromUtf8("txtIPv6AddressConfig"))
        self.lineEdit_2 = QtGui.QLineEdit(self.tabConfig)
        self.lineEdit_2.setGeometry(QtCore.QRect(102, 50, 261, 20))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.txtPrivateKey = QtGui.QTextBrowser(self.tabConfig)
        self.txtPrivateKey.setGeometry(QtCore.QRect(100, 91, 421, 211))
        self.txtPrivateKey.setObjectName(_fromUtf8("txtPrivateKey"))
        self.cmdLoadPrivateKey = QtGui.QPushButton(self.tabConfig)
        self.cmdLoadPrivateKey.setGeometry(QtCore.QRect(530, 90, 75, 23))
        self.cmdLoadPrivateKey.setObjectName(_fromUtf8("cmdLoadPrivateKey"))
        self.cmdGenerateAddress = QtGui.QPushButton(self.tabConfig)
        self.cmdGenerateAddress.setGeometry(QtCore.QRect(450, 12, 75, 31))
        self.cmdGenerateAddress.setObjectName(_fromUtf8("cmdGenerateAddress"))
        self.tabContainer.addTab(self.tabConfig, _fromUtf8(""))
        self.cmdQuit = QtGui.QPushButton(self.centralWidget)
        self.cmdQuit.setGeometry(QtCore.QRect(750, 390, 75, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.cmdQuit.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cmdQuit.setFont(font)
        self.cmdQuit.setAutoFillBackground(False)
        self.cmdQuit.setDefault(False)
        self.cmdQuit.setObjectName(_fromUtf8("cmdQuit"))
        frmMain.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(frmMain)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 845, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuContacts = QtGui.QMenu(self.menuBar)
        self.menuContacts.setObjectName(_fromUtf8("menuContacts"))
        frmMain.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(frmMain)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        frmMain.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(frmMain)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        frmMain.setStatusBar(self.statusBar)
        self.actionContacts = QtGui.QAction(frmMain)
        self.actionContacts.setObjectName(_fromUtf8("actionContacts"))
        self.actionGroups = QtGui.QAction(frmMain)
        self.actionGroups.setObjectName(_fromUtf8("actionGroups"))
        self.actionQuit = QtGui.QAction(frmMain)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionConfiguration = QtGui.QAction(frmMain)
        self.actionConfiguration.setObjectName(_fromUtf8("actionConfiguration"))
        self.menuContacts.addAction(self.actionContacts)
        self.menuContacts.addAction(self.actionGroups)
        self.menuContacts.addAction(self.actionConfiguration)
        self.menuContacts.addAction(self.actionQuit)
        self.menuBar.addAction(self.menuContacts.menuAction())

        self.retranslateUi(frmMain)
        self.tabContainer.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(frmMain)

    def retranslateUi(self, frmMain):
        frmMain.setWindowTitle(QtGui.QApplication.translate("frmMain", "IPv6 Secure Messenger", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdSend.setText(QtGui.QApplication.translate("frmMain", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdClear.setText(QtGui.QApplication.translate("frmMain", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSendingTo.setText(QtGui.QApplication.translate("frmMain", "Sending To:", None, QtGui.QApplication.UnicodeUTF8))
        self.treeContacts.headerItem().setText(0, QtGui.QApplication.translate("frmMain", "Messenger", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.treeContacts.isSortingEnabled()
        self.treeContacts.setSortingEnabled(False)
        self.treeContacts.topLevelItem(0).setText(0, QtGui.QApplication.translate("frmMain", "Contacts", None, QtGui.QApplication.UnicodeUTF8))
        self.treeContacts.topLevelItem(1).setText(0, QtGui.QApplication.translate("frmMain", "Groups", None, QtGui.QApplication.UnicodeUTF8))
        self.treeContacts.setSortingEnabled(__sortingEnabled)
        self.tabContainer.setTabText(self.tabContainer.indexOf(self.tabComms), QtGui.QApplication.translate("frmMain", "Comms", None, QtGui.QApplication.UnicodeUTF8))
        self.tabContainer.setTabText(self.tabContainer.indexOf(self.tabWeb), QtGui.QApplication.translate("frmMain", "Web", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBio.setText(QtGui.QApplication.translate("frmMain", "Bio:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblV6Address.setText(QtGui.QApplication.translate("frmMain", "IPv6 Address", None, QtGui.QApplication.UnicodeUTF8))
        self.lblUserName.setText(QtGui.QApplication.translate("frmMain", "User Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdUpdateProfile.setText(QtGui.QApplication.translate("frmMain", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdCancelProfile.setText(QtGui.QApplication.translate("frmMain", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.tabContainer.setTabText(self.tabContainer.indexOf(self.tabProfile), QtGui.QApplication.translate("frmMain", "My Profile", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdSaveConfig.setText(QtGui.QApplication.translate("frmMain", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.lblIPv6ConfigAddress.setText(QtGui.QApplication.translate("frmMain", "IPv6 Address:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPassword.setText(QtGui.QApplication.translate("frmMain", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPrivateKey.setText(QtGui.QApplication.translate("frmMain", "Private Key:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdLoadPrivateKey.setText(QtGui.QApplication.translate("frmMain", "Load...", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdGenerateAddress.setText(QtGui.QApplication.translate("frmMain", "Generate", None, QtGui.QApplication.UnicodeUTF8))
        self.tabContainer.setTabText(self.tabContainer.indexOf(self.tabConfig), QtGui.QApplication.translate("frmMain", "Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdQuit.setText(QtGui.QApplication.translate("frmMain", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuContacts.setTitle(QtGui.QApplication.translate("frmMain", "Messenger", None, QtGui.QApplication.UnicodeUTF8))
        self.actionContacts.setText(QtGui.QApplication.translate("frmMain", "Contacts", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGroups.setText(QtGui.QApplication.translate("frmMain", "Groups", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("frmMain", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfiguration.setText(QtGui.QApplication.translate("frmMain", "Configuration", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    frmMain = QtGui.QMainWindow()
    ui = Ui_frmMain()
    ui.setupUi(frmMain)
    frmMain.show()
    sys.exit(app.exec_())

